//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Attachments.BLL
{
    
    
    public partial class AttachmentBLL : Framework.Attachments.BLL.SecurityDomainBLLBase<Framework.Attachments.Domain.Attachment, Framework.DomainDriven.BLL.BLLBaseOperation>, Framework.Attachments.BLL.IAttachmentBLL
    {
        
		partial void Initialize();
        
        public AttachmentBLL(Framework.Attachments.BLL.IAttachmentsBLLContext context, Framework.SecuritySystem.ISecurityProvider<Framework.Attachments.Domain.Attachment> securityProvider, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, securityProvider, specificationEvaluator)
        {
            this.Initialize();
        }
    }
    
    public partial class AttachmentBLLFactory : Framework.DomainDriven.BLL.Security.SecurityBLLFactory<Framework.Attachments.BLL.IAttachmentsBLLContext, Framework.Attachments.BLL.IAttachmentBLL, Framework.Attachments.BLL.AttachmentBLL, Framework.Attachments.Domain.Attachment>, Framework.Attachments.BLL.IAttachmentBLLFactory
    {
        
        public AttachmentBLLFactory(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
    }
    
    public partial class AttachmentContainerBLL : Framework.Attachments.BLL.SecurityDomainBLLBase<Framework.Attachments.Domain.AttachmentContainer, Framework.DomainDriven.BLL.BLLBaseOperation>, Framework.Attachments.BLL.IAttachmentContainerBLL
    {
        
		partial void Initialize();
        
        public AttachmentContainerBLL(Framework.Attachments.BLL.IAttachmentsBLLContext context, Framework.SecuritySystem.ISecurityProvider<Framework.Attachments.Domain.AttachmentContainer> securityProvider, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, securityProvider, specificationEvaluator)
        {
            this.Initialize();
        }
    }
    
    public partial class AttachmentContainerBLLFactory : Framework.DomainDriven.BLL.Security.SecurityBLLFactory<Framework.Attachments.BLL.IAttachmentsBLLContext, Framework.Attachments.BLL.IAttachmentContainerBLL, Framework.Attachments.BLL.AttachmentContainerBLL, Framework.Attachments.Domain.AttachmentContainer>, Framework.Attachments.BLL.IAttachmentContainerBLLFactory
    {
        
        public AttachmentContainerBLLFactory(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
    }
    
    public partial class DomainTypeBLL : Framework.Attachments.BLL.SecurityDomainBLLBase<Framework.Attachments.Domain.DomainType, Framework.DomainDriven.BLL.BLLBaseOperation>, Framework.Attachments.BLL.IDomainTypeBLL
    {
        
		partial void Initialize();
        
        public DomainTypeBLL(Framework.Attachments.BLL.IAttachmentsBLLContext context, Framework.SecuritySystem.ISecurityProvider<Framework.Attachments.Domain.DomainType> securityProvider, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, securityProvider, specificationEvaluator)
        {
            this.Initialize();
        }
    }
    
    public partial class DomainTypeBLLFactory : Framework.DomainDriven.BLL.Security.SecurityBLLFactory<Framework.Attachments.BLL.IAttachmentsBLLContext, Framework.Attachments.BLL.IDomainTypeBLL, Framework.Attachments.BLL.DomainTypeBLL, Framework.Attachments.Domain.DomainType>, Framework.Attachments.BLL.IDomainTypeBLLFactory
    {
        
        public DomainTypeBLLFactory(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
    }
    
    public partial class TargetSystemBLL : Framework.Attachments.BLL.SecurityDomainBLLBase<Framework.Attachments.Domain.TargetSystem, Framework.DomainDriven.BLL.BLLBaseOperation>, Framework.Attachments.BLL.ITargetSystemBLL
    {
        
		partial void Initialize();
        
        public TargetSystemBLL(Framework.Attachments.BLL.IAttachmentsBLLContext context, Framework.SecuritySystem.ISecurityProvider<Framework.Attachments.Domain.TargetSystem> securityProvider, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, securityProvider, specificationEvaluator)
        {
            this.Initialize();
        }
    }
    
    public partial class TargetSystemBLLFactory : Framework.DomainDriven.BLL.Security.SecurityBLLFactory<Framework.Attachments.BLL.IAttachmentsBLLContext, Framework.Attachments.BLL.ITargetSystemBLL, Framework.Attachments.BLL.TargetSystemBLL, Framework.Attachments.Domain.TargetSystem>, Framework.Attachments.BLL.ITargetSystemBLLFactory
    {
        
        public TargetSystemBLLFactory(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
    }
    
    public partial class AttachmentsBLLFactoryContainer : Framework.DomainDriven.BLL.BLLContextContainer<Framework.Attachments.BLL.IAttachmentsBLLContext>, Framework.Attachments.BLL.IAttachmentsBLLFactoryContainer
    {
        
        private Framework.Attachments.BLL.IAttachmentBLL attachmentBLL;
        
        private Framework.Attachments.BLL.IAttachmentContainerBLL attachmentContainerBLL;
        
        private Framework.Attachments.BLL.AttachmentsDefaultBLLFactory defaultBLLFactory;
        
        private Framework.Attachments.BLL.IDomainTypeBLL domainTypeBLL;
        
        private Framework.Attachments.BLL.AttachmentsImplementedBLLFactory implementedBLLFactory;
        
        private Framework.Attachments.BLL.ITargetSystemBLL targetSystemBLL;
        
        public AttachmentsBLLFactoryContainer(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
        
        public Framework.Attachments.BLL.IAttachmentBLL Attachment
        {
            get
            {
                if (object.ReferenceEquals(this.attachmentBLL, null))
                {
                    this.attachmentBLL = this.AttachmentFactory.Create();
                }
                return this.attachmentBLL;
            }
        }
        
        public Framework.Attachments.BLL.IAttachmentContainerBLL AttachmentContainer
        {
            get
            {
                if (object.ReferenceEquals(this.attachmentContainerBLL, null))
                {
                    this.attachmentContainerBLL = this.AttachmentContainerFactory.Create();
                }
                return this.attachmentContainerBLL;
            }
        }
        
        public Framework.Attachments.BLL.IAttachmentContainerBLLFactory AttachmentContainerFactory
        {
            get
            {
                return Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Framework.Attachments.BLL.IAttachmentContainerBLLFactory>(this.Context.ServiceProvider);
            }
        }
        
        public Framework.Attachments.BLL.IAttachmentBLLFactory AttachmentFactory
        {
            get
            {
                return Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Framework.Attachments.BLL.IAttachmentBLLFactory>(this.Context.ServiceProvider);
            }
        }
        
        public Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<Framework.Attachments.Domain.PersistentDomainObjectBase, System.Guid> Default
        {
            get
            {
                if (object.ReferenceEquals(this.defaultBLLFactory, null))
                {
                    this.defaultBLLFactory = new Framework.Attachments.BLL.AttachmentsDefaultBLLFactory(this.Context);
                }
                return this.defaultBLLFactory;
            }
        }
        
        public Framework.Attachments.BLL.IDomainTypeBLL DomainType
        {
            get
            {
                if (object.ReferenceEquals(this.domainTypeBLL, null))
                {
                    this.domainTypeBLL = this.DomainTypeFactory.Create();
                }
                return this.domainTypeBLL;
            }
        }
        
        public Framework.Attachments.BLL.IDomainTypeBLLFactory DomainTypeFactory
        {
            get
            {
                return Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Framework.Attachments.BLL.IDomainTypeBLLFactory>(this.Context.ServiceProvider);
            }
        }
        
        public Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<Framework.Attachments.Domain.PersistentDomainObjectBase, System.Guid> Implemented
        {
            get
            {
                if (object.ReferenceEquals(this.implementedBLLFactory, null))
                {
                    this.implementedBLLFactory = new Framework.Attachments.BLL.AttachmentsImplementedBLLFactory(this.Context);
                }
                return this.implementedBLLFactory;
            }
        }
        
        public Framework.Attachments.BLL.ITargetSystemBLL TargetSystem
        {
            get
            {
                if (object.ReferenceEquals(this.targetSystemBLL, null))
                {
                    this.targetSystemBLL = this.TargetSystemFactory.Create();
                }
                return this.targetSystemBLL;
            }
        }
        
        public Framework.Attachments.BLL.ITargetSystemBLLFactory TargetSystemFactory
        {
            get
            {
                return Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<Framework.Attachments.BLL.ITargetSystemBLLFactory>(this.Context.ServiceProvider);
            }
        }
        
        public static void RegisterBLLFactory(Microsoft.Extensions.DependencyInjection.IServiceCollection serviceCollection)
        {
            Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<Framework.Attachments.BLL.IAttachmentBLLFactory, Framework.Attachments.BLL.AttachmentBLLFactory>(serviceCollection);
            Framework.DependencyInjection.ServiceCollectionExtensions.AddScopedFrom<Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<Framework.Attachments.Domain.PersistentDomainObjectBase, Framework.Attachments.Domain.Attachment, System.Guid>, Framework.Attachments.Domain.Attachment>, Framework.Attachments.BLL.IAttachmentBLLFactory>(serviceCollection);
            Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<Framework.Attachments.BLL.IAttachmentContainerBLLFactory, Framework.Attachments.BLL.AttachmentContainerBLLFactory>(serviceCollection);
            Framework.DependencyInjection.ServiceCollectionExtensions.AddScopedFrom<Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<Framework.Attachments.Domain.PersistentDomainObjectBase, Framework.Attachments.Domain.AttachmentContainer, System.Guid>, Framework.Attachments.Domain.AttachmentContainer>, Framework.Attachments.BLL.IAttachmentContainerBLLFactory>(serviceCollection);
            Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<Framework.Attachments.BLL.IDomainTypeBLLFactory, Framework.Attachments.BLL.DomainTypeBLLFactory>(serviceCollection);
            Framework.DependencyInjection.ServiceCollectionExtensions.AddScopedFrom<Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<Framework.Attachments.Domain.PersistentDomainObjectBase, Framework.Attachments.Domain.DomainType, System.Guid>, Framework.Attachments.Domain.DomainType>, Framework.Attachments.BLL.IDomainTypeBLLFactory>(serviceCollection);
            Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<Framework.Attachments.BLL.ITargetSystemBLLFactory, Framework.Attachments.BLL.TargetSystemBLLFactory>(serviceCollection);
            Framework.DependencyInjection.ServiceCollectionExtensions.AddScopedFrom<Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<Framework.Attachments.Domain.PersistentDomainObjectBase, Framework.Attachments.Domain.TargetSystem, System.Guid>, Framework.Attachments.Domain.TargetSystem>, Framework.Attachments.BLL.ITargetSystemBLLFactory>(serviceCollection);
        }
    }
    
    public partial class AttachmentsDefaultBLLFactory : Framework.DomainDriven.BLL.Security.DefaultSecurityBLLFactory<Framework.Attachments.BLL.IAttachmentsBLLContext, Framework.Attachments.Domain.PersistentDomainObjectBase, System.Guid>, Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<Framework.Attachments.Domain.PersistentDomainObjectBase, System.Guid>
    {
        
        public AttachmentsDefaultBLLFactory(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
        
        public override Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<Framework.Attachments.Domain.PersistentDomainObjectBase, TDomainObject, System.Guid> Create<TDomainObject>(Framework.SecuritySystem.ISecurityProvider<TDomainObject> securityProvider)
        {
            return new Framework.Attachments.BLL.SecurityDomainBLLBase<TDomainObject>(this.Context, securityProvider);
        }
    }
    
    public partial class AttachmentsImplementedBLLFactory : Framework.DomainDriven.BLL.Security.ImplementedSecurityBLLFactory<Framework.Attachments.BLL.IAttachmentsBLLContext, Framework.Attachments.Domain.PersistentDomainObjectBase, System.Guid>, Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<Framework.Attachments.Domain.PersistentDomainObjectBase, System.Guid>
    {
        
        public AttachmentsImplementedBLLFactory(Framework.Attachments.BLL.IAttachmentsBLLContext context) : 
                base(context)
        {
        }
        
        protected override Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<Framework.Attachments.Domain.PersistentDomainObjectBase, TDomainObject, System.Guid> CreateDefault<TDomainObject>(Framework.SecuritySystem.ISecurityProvider<TDomainObject> securityProvider)
        {
            return new Framework.Attachments.BLL.SecurityDomainBLLBase<TDomainObject>(this.Context, securityProvider);
        }
    }
}
