//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttachmentsSampleSystem.BLL
{
    
    
    public partial class AttachmentsSampleSystemBLLContext : Framework.DomainDriven.BLL.Security.SecurityBLLBaseContext<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid, AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLFactoryContainer>, Framework.DomainDriven.BLL.IBLLFactoryContainerContext<Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>>, AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext
    {
        
        Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.IDefaultBLLFactory<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>> Framework.DomainDriven.BLL.IBLLFactoryContainerContext<Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.IDefaultBLLFactory<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>>.Logics
        {
            get
            {
                return this.Logics;
            }
        }
        
        Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>> Framework.DomainDriven.BLL.IBLLFactoryContainerContext<Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>>.Logics
        {
            get
            {
                return this.Logics;
            }
        }
    }
    
    public partial interface IAttachmentsSampleSystemBLLContext : Framework.DomainDriven.BLL.Security.IAccessDeniedExceptionServiceContainer, Framework.DomainDriven.BLL.Security.ISecurityServiceContainer<Framework.DomainDriven.BLL.Security.IRootSecurityService<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase>>, Framework.DomainDriven.BLL.IBLLFactoryContainerContext<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLFactoryContainer>, Framework.DomainDriven.IFetchServiceContainer<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, Framework.DomainDriven.FetchBuildRule>
    {
        
        new AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLFactoryContainer Logics
        {
            get;
        }
    }
    
    public partial class SecurityDomainBLLBase<TDomainObject, TOperation> : Framework.DomainDriven.BLL.Security.DefaultSecurityDomainBLLBase<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, TDomainObject, System.Guid, TOperation>
        where TDomainObject : AttachmentsSampleSystem.Domain.PersistentDomainObjectBase
        where TOperation :  struct, System.Enum
    {
        
        public SecurityDomainBLLBase(AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext context, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, specificationEvaluator)
        {
        }
        
        public SecurityDomainBLLBase(AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext context, Framework.SecuritySystem.ISecurityProvider<TDomainObject> securityProvider, nuSpec.Abstraction.ISpecificationEvaluator specificationEvaluator = null) : 
                base(context, securityProvider, specificationEvaluator)
        {
        }
    }
    
    public partial class SecurityDomainBLLBase<TDomainObject> : AttachmentsSampleSystem.BLL.SecurityDomainBLLBase<TDomainObject, Framework.DomainDriven.BLL.BLLBaseOperation>
        where TDomainObject : AttachmentsSampleSystem.Domain.PersistentDomainObjectBase
    {
        
        public SecurityDomainBLLBase(AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext context) : 
                base(context)
        {
        }
        
        public SecurityDomainBLLBase(AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext context, Framework.SecuritySystem.ISecurityProvider<TDomainObject> securityProvider) : 
                base(context, securityProvider)
        {
        }
    }
    
    public partial interface IAttachmentsSampleSystemBLLFactoryContainer : Framework.DomainDriven.BLL.IBLLFactoryContainer<Framework.DomainDriven.BLL.Security.IDefaultSecurityBLLFactory<AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, System.Guid>>
    {
        
        AttachmentsSampleSystem.BLL.IBusinessUnitBLL BusinessUnit
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.IBusinessUnitBLLFactory BusinessUnitFactory
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.IEmployeeBLL Employee
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.IEmployeeBLLFactory EmployeeFactory
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.IHRDepartmentBLL HRDepartment
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.IHRDepartmentBLLFactory HRDepartmentFactory
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.ILocationBLL Location
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.ILocationBLLFactory LocationFactory
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.INamedLockBLL NamedLock
        {
            get;
        }
        
        AttachmentsSampleSystem.BLL.INamedLockBLLFactory NamedLockFactory
        {
            get;
        }
    }
    
    public partial interface IBusinessUnitBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, AttachmentsSampleSystem.Domain.BusinessUnit, System.Guid>
    {
    }
    
    public partial interface IBusinessUnitBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<AttachmentsSampleSystem.BLL.IBusinessUnitBLL, AttachmentsSampleSystem.Domain.BusinessUnit>
    {
    }
    
    public partial interface IEmployeeBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, AttachmentsSampleSystem.Domain.Employee, System.Guid>
    {
    }
    
    public partial interface IEmployeeBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<AttachmentsSampleSystem.BLL.IEmployeeBLL, AttachmentsSampleSystem.Domain.Employee>
    {
    }
    
    public partial interface IHRDepartmentBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, AttachmentsSampleSystem.Domain.HRDepartment, System.Guid>
    {
    }
    
    public partial interface IHRDepartmentBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<AttachmentsSampleSystem.BLL.IHRDepartmentBLL, AttachmentsSampleSystem.Domain.HRDepartment>
    {
    }
    
    public partial interface ILocationBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, AttachmentsSampleSystem.Domain.Location, System.Guid>
    {
    }
    
    public partial interface ILocationBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<AttachmentsSampleSystem.BLL.ILocationBLL, AttachmentsSampleSystem.Domain.Location>
    {
    }
    
    public partial interface INamedLockBLL : Framework.DomainDriven.BLL.Security.IDefaultSecurityDomainBLLBase<AttachmentsSampleSystem.BLL.IAttachmentsSampleSystemBLLContext, AttachmentsSampleSystem.Domain.PersistentDomainObjectBase, AttachmentsSampleSystem.Domain.NamedLock, System.Guid>
    {
    }
    
    public partial interface INamedLockBLLFactory : Framework.DomainDriven.BLL.Security.ISecurityBLLFactory<AttachmentsSampleSystem.BLL.INamedLockBLL, AttachmentsSampleSystem.Domain.NamedLock>
    {
    }
}
